### ISSUE TITLE
console error when we hover over the chart when all the series are toggled OFF

### ISSUE THREAD

**Issue by kkarkal** [amcharts/amcharts5#1176]
**Bug description**

We have multiple series in our XY Chart i.e two line series and one column series. When we toggle off all our series by clicking on the legend and hover over the chart area, It gives the console error like this:

```
main.ts:28 TypeError: Cannot read properties of undefined (reading 'x')
    at XYChart.js:1220:1
    at Module.each (Array.js:73:1)
    at ListAutoDispose.each (List.js:369:9)
    at XYChart.arrangeTooltips (XYChart.js:1210:1)
    at XYCursor.handleMove (XYCursor.js:508:1)
    at XYCursor._handleMove (XYCursor.js:429:1)
    at XYCursor.js:333:1
    at Object.dispatch (EventDispatcher.js:390:97)
    at EventDispatcher.js:293:30
    at Module.each (Array.js:73:1)
    at SpriteEventDispatcher._eachListener (EventDispatcher.js:266:13)
    at SpriteEventDispatcher.dispatch (EventDispatcher.js:291:18)
    at SpriteEventDispatcher.globalpointermove (Sprite.js:177:1)
    at Sprite.js:59:1
    at CanvasRenderer.js:3848:1
    at Module.each (Array.js:73:1)
    at CanvasRenderer.js:3846:13
    at CanvasRenderer._withEvents (CanvasRenderer.js:3824:1)
    at CanvasRenderer._dispatchEventAll (CanvasRenderer.js:3845:1)
    at CanvasRenderer._dispatchGlobalMousemove (CanvasRenderer.js:3934:1)
    at CanvasRenderer.js:4076:1
    at Module.each (Array.js:73:1)
    at listener (CanvasRenderer.js:4075:25)
    at CanvasRenderer.js:4061:1
    at CanvasRenderer.js:170:1
    at sentryWrapped (helpers.js:74:23)
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.js:28767:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:1)
    at invokeTask (zone.js:1661:1)
    at globalCallback (zone.js:1704:1)
    at globalZoneAwareCallback (zone.js:1725:1)
```

This issue is only reproduced when all the series are toggled OFF and when we hover over our chart area.

**Environment (if applicable)**

 - amCharts version : 5
 - Browser and its version: Google Chrome Version 119.0.6045.105 (Official Build) (64-bit)
 - Related frameworks and their versions [e.g. Angular, TypeScript, etc.] : Angular 12

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by kkarkal** [comment]
I will add it on codepen and share it here, please give me sometime.
