### ISSUE TITLE
The `afterEach` is based on your code which you provided earlier.

### ISSUE THREAD

**Issue by brijesh-imemori** [amcharts/amcharts5#1303]
The `afterEach` is based on your code which you provided earlier.

[Our docs](https://www.amcharts.com/docs/v5/getting-started/integrations/jest/) show how to set up everything correctly (including the tests), and we have a [working example](https://stackblitz.com/edit/node-mm8hqa?file=src%2FApp.js).

_Originally posted by @Pauan in https://github.com/amcharts/amcharts5/issues/1223#issuecomment-1858419270_

**Comment by brijesh-imemori** [comment]
> ```
>           The `afterEach` is based on your code which you provided earlier.
> ```
> 
> [Our docs](https://www.amcharts.com/docs/v5/getting-started/integrations/jest/) show how to set up everything correctly (including the tests), and we have a [working example](https://stackblitz.com/edit/node-mm8hqa?file=src%2FApp.js).
> 
> _Originally posted by @Pauan in [#1223 (comment)](https://github.com/amcharts/amcharts5/issues/1223#issuecomment-1858419270)_



Hi @Pauan , this is what I get on the provided stackblitz when I do the **npm test** on terminal

`~/projects/node-mm8hqa
❯ npm test

> node-mm8hqa@0.1.0 test
> react-scripts test --env jsdom --watchAll=false

 FAIL  src/chart.test.js
  ● Test suite failed to run

    Cannot find module '../build/Release/canvas.node'
    Require stack:
    - /home/projects/node-mm8hqa/node_modules/canvas/lib/bindings.js
    - /home/projects/node-mm8hqa/node_modules/canvas/lib/canvas.js
    - /home/projects/node-mm8hqa/node_modules/canvas/index.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/utils.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/living/events/MouseEvent-impl.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/living/generated/MouseEvent.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/living/interfaces.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/browser/Window.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/api.js
    - /home/projects/node-mm8hqa/node_modules/jest-environment-jsdom/build/index.js
    - /home/projects/node-mm8hqa/node_modules/jest-util/build/requireOrImportModule.js
    - /home/projects/node-mm8hqa/node_modules/jest-util/build/index.js
    - /home/projects/node-mm8hqa/node_modules/jest-resolve/build/resolver.js
    - /home/projects/node-mm8hqa/node_modules/jest-resolve/build/index.js
    - /home/projects/node-mm8hqa/node_modules/jest-runtime/build/index.js
    - /home/projects/node-mm8hqa/node_modules/jest-runner/build/testWorker.js
    - /home/projects/node-mm8hqa/node_modules/jest-worker/build/workers/processChild.js

      at Module._resolveFilename (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:12642)
      at Module._load (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:10056)
      at Module.require (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:13775)
      at i (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:98:2198)
      at _0x3f4f2e (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:352:193969)
      at Object.eval (file:/home/projects/node-mm8hqa/node_modules/canvas/lib/bindings.js:3:18)
      at Object.function (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:352:194769)
      at Module._compile (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:14871)
      at Module._extensions..js (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:15550)
      at Module.load (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:13457)

 FAIL  src/App.test.js
  ● Test suite failed to run

    Cannot find module '../build/Release/canvas.node'
    Require stack:
    - /home/projects/node-mm8hqa/node_modules/canvas/lib/bindings.js
    - /home/projects/node-mm8hqa/node_modules/canvas/lib/canvas.js
    - /home/projects/node-mm8hqa/node_modules/canvas/index.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/utils.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/living/events/MouseEvent-impl.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/living/generated/MouseEvent.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/living/interfaces.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/browser/Window.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/api.js
    - /home/projects/node-mm8hqa/node_modules/jest-environment-jsdom/build/index.js
    - /home/projects/node-mm8hqa/node_modules/jest-util/build/requireOrImportModule.js
    - /home/projects/node-mm8hqa/node_modules/jest-util/build/index.js
    - /home/projects/node-mm8hqa/node_modules/jest-resolve/build/resolver.js
    - /home/projects/node-mm8hqa/node_modules/jest-resolve/build/index.js
    - /home/projects/node-mm8hqa/node_modules/jest-runtime/build/index.js
    - /home/projects/node-mm8hqa/node_modules/jest-runner/build/testWorker.js
    - /home/projects/node-mm8hqa/node_modules/jest-worker/build/workers/processChild.js

      at Module._resolveFilename (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:12642)
      at Module._load (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:10056)
      at Module.require (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:13775)
      at i (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:98:2198)
      at _0x3f4f2e (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:352:193969)
      at Object.eval (file:/home/projects/node-mm8hqa/node_modules/canvas/lib/bindings.js:3:18)
      at Object.function (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:352:194769)
      at Module._compile (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:14871)
      at Module._extensions..js (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:15550)
      at Module.load (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:13457)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        2.539 s
Ran all test suites.`

**Comment by Pauan** [comment]
@brijesh-imemori That error means that you did not install `canvas` correctly.

When running `yarn install`, pay careful attention to any errors or warnings.

Please follow [these instructions](https://github.com/Automattic/node-canvas/issues/1511) for installing `canvas`.

**Comment by brijesh-imemori** [comment]
https://github.com/jestjs/jest/issues/6229#issuecomment-590737867

this issue helped us to fix the issue, thank you so much for your support @Pauan
