### ISSUE TITLE
World map rendering using amchart5 

### ISSUE THREAD

**Issue by gnaneswaran999** [amcharts/amcharts5#1396]
**Bug description**

if i try render world map in amchart 5 , it is showing blank page and giving an error related makecontainer and not able to solve it.

code:
```
import React, { useEffect, useRef } from 'react';
import * as am5 from "@amcharts/amcharts5";
import * as am5map from "@amcharts/amcharts5/map";
import "@amcharts/amcharts5-geodata/worldLow";

const WorldMapChart = () => {
  const chartDivRef = useRef(null);

  useEffect(() => {
    const chartDiv = chartDivRef.current;

    if (chartDiv) {
      try {
        let chart = am5.Chart.new(chartDiv, am5map.MapChart);
        chart.setMapSource("@amcharts/amcharts5-geodata/worldLow");

        // Clean up chart on unmount
        return () => {
          if (chart) {
            chart.dispose();
          }
        };
      } catch (error) {
        console.error("Error creating amCharts map:", error);
      }
    } else {
      console.warn("Chart container element not found. Please ensure the div with ID 'chartdiv' exists.");
    }
  }, []);

  return (
    <div ref={chartDivRef} id="chartdiv" style={{ width: "100%", height: "500px" }}></div>
  );
};

export default WorldMapChart;
```

and error message is 
```
WorldMap.js:24 Error creating amCharts map: TypeError: Cannot read properties of undefined (reading 'makeContainer')
    at new Container (Container.ts:136:1)
    at new Chart (Chart.ts:16:1)
    at Chart.new (Entity.ts:992:1)
    at WorldMap.js:14:1
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)
    at commitPassiveMountEffects (react-dom.development.js:24866:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:1)
(anonymous) @ WorldMap.js:24
WorldMap.js:24 Error creating amCharts map: TypeError: Cannot read properties of undefined (reading 'makeContainer')
    at new Container (Container.ts:136:1)
    at new Chart (Chart.ts:16:1)
    at Chart.new (Entity.ts:992:1)
    at WorldMap.js:14:1
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at invokePassiveEffectMountInDEV (react-dom.development.js:25154:1)
    at invokeEffectsInDev (react-dom.development.js:27351:1)
    at commitDoubleInvokeEffectsInDEV (react-dom.development.js:27330:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27056:1)
    at flushPassiveEffects (react-dom.development.js:26984:1)
(anonymous) @ WorldMap.js:24
main.afea3d053bfd3efa59a3.hot-update.js:44 Error creating amCharts map: TypeError: Cannot read properties of undefined (reading 'makeContainer')
    at new Container (Container.ts:136:1)
    at new Chart (Chart.ts:16:1)
    at Chart.new (Entity.ts:992:1)
    at main.afea3d053bfd3efa59a3.hot-update.js:38:79
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)
    at commitPassiveMountEffects (react-dom.development.js:24866:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:1)
```

**Comment by gnaneswaran999** [comment]
solve it as soon as possible
