### ISSUE TITLE
Custom theme throws error (_.lookupRules)

### ISSUE THREAD

**Issue by rferreira98** [amcharts/amcharts5#315]
I have used DarkTheme as example but not even this one works.

CustomTheme.js

```

import { Theme, Color } from "@amcharts/amcharts5";

export class CustomTheme extends Theme {
    setupDefaultRules() {
        super.setupDefaultRules();

        this.rule("InterfaceColors").setAll({
            stroke: Color.fromHex(0x000000),
            fill: Color.fromHex(0x2b2b2b),
            primaryButton: Color.lighten(Color.fromHex(0x6794dc), -0.2),
            primaryButtonHover: Color.lighten(Color.fromHex(0x6771dc), -0.2),
            primaryButtonDown: Color.lighten(Color.fromHex(0x68dc75), -0.2),
            primaryButtonActive: Color.lighten(Color.fromHex(0x68dc76), -0.2),
            primaryButtonText: Color.fromHex(0xffffff),
            primaryButtonStroke: Color.lighten(Color.fromHex(0x6794dc), -0.2),

            secondaryButton: Color.fromHex(0x3b3b3b),
            secondaryButtonHover: Color.lighten(Color.fromHex(0x3b3b3b), 0.1),
            secondaryButtonDown: Color.lighten(Color.fromHex(0x3b3b3b), 0.15),
            secondaryButtonActive: Color.lighten(Color.fromHex(0x3b3b3b), 0.2),
            secondaryButtonText: Color.fromHex(0xbbbbbb),
            secondaryButtonStroke: Color.lighten(Color.fromHex(0x3b3b3b), -0.2),

            grid: Color.fromHex(0xbbbbbb),
            background: Color.fromHex(0x000000),
            alternativeBackground: Color.fromHex(0xffffff),
            text: Color.fromHex(0xffffff),
            alternativeText: Color.fromHex(0x000000),
            disabled: Color.fromHex(0xadadad),
            positive: Color.fromHex(0x50b300),
            negative: Color.fromHex(0xb30000)
        });

    }
}

```

And I'm importing in my PieChart this way:

```

import { CustomTheme } from "./CustomTheme";
.
.
.
root.setThemes([
  CustomTheme
]);

```

And the error is the following:

```
Entity.ts:1514 Uncaught TypeError: theme._lookupRules is not a function
    at Entity.ts:1514:1
    at Module.each (Array.ts:93:1)
    at Entity.ts:1513:1
    at Module.each (Array.ts:93:1)
    at Entity.ts:1512:1
    at Module.eachReverse (Array.ts:109:1)
    at Container.value (Entity.ts:1509:1)
    at Container.value (Container.ts:271:1)
    at Root.value (Root.ts:951:1)
    at PieChart.js:11:1

```

**Comment by martynasma** [comment]
You need to instantiate the theme like this:

```JavaScript
root.setThemes([
  CustomTheme.new(root);
]);
```

**Comment by rferreira98** [comment]
That was the problem. Thank you.
