### ISSUE TITLE
JEST + NXWorkspace + Amchart5 throws error

### ISSUE THREAD

**Issue by 3gwebtrain** [amcharts/amcharts5#526]
Angular testing file :

```
import { ComponentFixture, TestBed } from '@angular/core/testing';

import * as am5 from '@amcharts/amcharts5';
import am5themes_Animated from '@amcharts/amcharts5/themes/Animated';
import * as am5xy from '@amcharts/amcharts5/xy';
import { ImplantReportComponent } from './implant-report.component';
describe('ImplantReportComponent', () => {
  let component: ImplantReportComponent;
  let fixture: ComponentFixture<ImplantReportComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [ImplantReportComponent],
      imports: [am5, am5xy, am5themes_Animated],
    }).compileComponents();
  });

  beforeEach(() => {
    fixture = TestBed.createComponent(ImplantReportComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
```
jest.preset.js:

```
const nxPreset = require('@nrwl/jest/preset').default;

module.exports = {
    ...nxPreset,
    testMatch: ['**/+(*.)+(spec|test).+(ts|js)?(x)'],
    transform: {
      '^.+\\.(ts|mjs|js|html)$': 'jest-preset-angular',
      "^.+\\.(js|jsx)$": "babel-jest-amcharts"
  },

    transformIgnorePatterns: ['node_modules/(?!.*\\.mjs$)', "[/\\\\]node_modules[/\\\\](?!(@amcharts)\\/).+\\.(js|jsx|ts|tsx)$",
    "^.+\\.module\\.(css|sass|scss)$"],
    resolver: '@nrwl/jest/plugins/resolver',
    coverageReporters: ['text', 'text-summary', "html", "cobertura"],
    moduleFileExtensions: ['ts', 'js', 'html'],
    globals: {
        crypto: require('crypto'),
        'ts-jest': {
            tsconfig: '<rootDir>/tsconfig.spec.json',
            stringifyContentPathRegex: '\\.(html|svg)$',
        },
    },
    snapshotSerializers: [
        'jest-preset-angular/build/serializers/no-ng-attributes',
        'jest-preset-angular/build/serializers/ng-snapshot',
        'jest-preset-angular/build/serializers/html-comment',
    ],
    "reporters": ["default", "jest-junit"]
};

```

on running the test getting the error as ;

```
 ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    C:\Users\BASHIMX5\Projects\Bitbucket\hf-ui\node_modules\@amcharts\amcharts5\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export { Root } from "./.internal/core/Root";
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

       8 |
       9 | // amCharts imports
    > 10 | import * as am5 from '@amcharts/amcharts5';
         | ^
      11 |
      12 | import * as am5xy from '@amcharts/amcharts5/xy';
      13 | import am5themes_Animated from '@amcharts/amcharts5/themes/Animated';

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (../../libs/tables/src/lib/graph-report-table/graph-report-table.component.ts:10:1)
```

I tried this as well : `https://www.amcharts.com/docs/v4/getting-started/using-typescript-or-es6/#Using_amCharts_with_Jest` but not works. any help?

**Comment by martynasma** [comment]
Maybe this will help:
https://www.amcharts.com/docs/v5/getting-started/integrations/jest/
